---
- name: Playbook desktop start
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  pre_tasks:
    - name: resolve remote user facts
      ansible.builtin.include_tasks: resolve_user.yml
      tags: always

  roles:
    - apt-sources-arcustech
    - base
    - unattended-upgrade-override
    - unbound
    - unbound-adblock
    #- vim # executes as local user, not root
    - env # executes as local user, not root
    - disable-local-dns
