---
- name: Playbook desktop start
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars.yml

  roles:
    - auto-update
    - base
    - ufw
    - unbound
    - unbound-adblock
      #- role: vim
      #become: false
    - role: env
      become: false
    - disable-local-dns
