---
- name: deploy unbound.conf template configuration file
  template:
    src: unbound.conf.j2
    dest: "/etc/unbound/unbound.conf.d/unbound.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  notify: reload unbound

- name: restart unbound service unconditionally
  meta: flush_handlers
