---
- name: Deploy unbound.conf template configuration file if it does not exist
  template:
    src: 00-server.conf.j2
    dest: "/etc/unbound/unbound.conf.d/server.d/00-server.conf"
    mode: "0644"
    owner: "root"
    group: "root"
  when: unbound_conf_stat.stat.exists == False
  notify: reload unbound
