---
- name: Ensure server.d directory exists for modular drop-ins
  file:
    path: /etc/unbound/unbound.conf.d/server.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Find all files from /etc/unbound/unbound.conf.d
  find:
    paths: /etc/unbound/unbound.conf.d
    file_type: file
  register: unbound_conf_files

- name: Check if 00-top-level-server.conf already exists (determine fresh install vs rerun)
  stat:
    path: /etc/unbound/unbound.conf.d/00-top-level-server.conf
  register: unbound_conf_stat

- name: Delete existing files for clean first deployment
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ unbound_conf_files.files }}"
  when: >
    unbound_conf_files.matched > 0 and
    unbound_conf_stat.stat.exists == False and
    item.path not in ['/etc/unbound/unbound.conf.d/00-top-level-server.conf',
                      '/etc/unbound/unbound.conf.d/server.d/10-server-local-dns.conf.example',
                      '/etc/unbound/unbound.conf.d/20-top-level-forward-zones.conf']
