---
- name: set unbound packages list
  set_fact:
    unbound_packages:
      - unbound
      - unbound-anchor
      - ca-certificates

- name: register unbound packages
  apt:
    name: "{{ unbound_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: _unbound_packages_result

- name: display intended unbound packages
  debug:
    msg: "{{ unbound_packages }}"

- name: show installed unbound packages
  debug:
    msg: "{{ _unbound_packages_result.stdout }}"
  when: _unbound_packages_result.changed

- name: ensure /var/lib/unbound directory exists
  file:
    path: /var/lib/unbound
    state: directory
    owner: unbound
    group: unbound
    mode: '0755'

- name: download the latest root.hints file
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: /var/lib/unbound/root.hints
    owner: unbound
    group: unbound
    mode: '0644'
    force: yes

- name: install root.key from IANA using unbound-anchor
  shell: '/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key'
  register: rootkey
  failed_when: rootkey.rc not in [0, 1]
  changed_when: "'success' in rootkey.stdout or rootkey.rc == 0"

- name: change ownership and group of root.key to unbound
  file:
    path: /var/lib/unbound/root.key
    owner: unbound
    group: unbound
    mode: '0640'
  when: rootkey.rc in [0, 1]

- name: create unbound systemd override directory
  file:
    path: /etc/systemd/system/unbound.service.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: configure unbound systemd service override file
  copy:
    dest: /etc/systemd/system/unbound.service.d/override.conf
    content: |
      [Service]
      Restart=on-failure
      RestartSec=5s
      TimeoutSec=10s
    mode: '0644'
    owner: root
    group: root
  notify:
    - reload systemd
    - restart unbound

- name: deploy local-dns Unbound file
  copy:
    src: 10-local-dns.conf.example
    dest: "/etc/unbound/unbound.conf.d/10-local-dns.conf.example"
    owner: root
    group: root
    mode: "0644"
  notify: reload unbound

- name: deploy forward-zone Unbound file
  copy:
    src: 20-forward-zones.conf
    dest: "/etc/unbound/unbound.conf.d/20-forward-zones.conf"
    owner: root
    group: root
    mode: "0644"
  notify: reload unbound
