---
- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache is valid for 1 hour

- name: Install Unbound and ca-certificates
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - unbound
    - unbound-anchor
    - ca-certificates
  loop_control:
    label: "{{ item }}"

- name: Ensure /var/lib/unbound directory exists
  file:
    path: /var/lib/unbound
    state: directory
    owner: unbound
    group: unbound
    mode: '0755'

- name: Download the latest root.hints file
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: /var/lib/unbound/root.hints
    owner: unbound
    group: unbound
    mode: '0644'
    force: yes

- name: Install root.key from IANA using unbound-anchor
  shell: '/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key'
  register: rootkey
  failed_when: rootkey.rc not in [0, 1]
  changed_when: "'success' in rootkey.stdout or rootkey.rc == 0"

- name: Change ownership and group of root.key to unbound
  file:
    path: /var/lib/unbound/root.key
    owner: unbound
    group: unbound
    mode: '0640'
  when: rootkey.rc in [0, 1]

- name: Create Unbound systemd override directory
  file:
    path: /etc/systemd/system/unbound.service.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Configure Unbound systemd service override file
  copy:
    dest: /etc/systemd/system/unbound.service.d/override.conf
    content: |
      [Service]
      Restart=on-failure
      RestartSec=5s
      TimeoutSec=10s
    mode: '0644'
    owner: root
    group: root
  notify:
    - reload systemd
    - restart unbound

- name: Deploy local-dns Unbound file
  copy:
    src: 10-server-local-dns.conf.example
    dest: "/etc/unbound/unbound.conf.d/server.d/10-server-local-dns.conf.example"
    owner: root
    group: root
    mode: "0644"
  notify: reload unbound

- name: Deploy forward-zone Unbound file
  copy:
    src: 20-top-level-forward-zones.conf
    dest: "/etc/unbound/unbound.conf.d/20-top-level-forward-zones.conf"
    owner: root
    group: root
    mode: "0644"
  notify: reload unbound
