- name: reload unbound
  service:
    name: unbound
    state: reloaded
  become: true

- name: restart unbound
  service:
    name: unbound
    state: restarted
  become: true

- name: start unbound
  service:
    name: unbound
    state: started
    enabled: yes
  become: true

- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: reload ufw
  command: ufw reload
  become: true
