---
# - name: reload unbound
#   service:
#     name: unbound
#     state: restarted

# - name: reload UFW
#   command: ufw reload

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Start Unbound
  systemd:
    name: unbound
    enabled: yes
    state: started
