- name: Reload unbound
  service:
    name: unbound
    state: reloaded

- name: Restart unbound
  service:
    name: unbound
    state: restarted

- name: Start unbound
  service:
    name: unbound
    state: started
    enabled: yes

- name: Reload systemd
  command: systemctl daemon-reload
