---
- name: packages | apt update && apt dist-upgrade *MAY TAKE A LONG TIME*
  apt:
    update_cache: true
    upgrade: dist

# keep alphabetically ordered
- name: packages | install standard additions to the base install
  apt:
    state: latest
    pkg: "{{ item }}"
  loop:
    - clamav
    - clamav-daemon
    - curl          # to be removed
    - dnsutils
    - fd-find
    - ripgrep
    - silversearcher-ag
    - tmux
    - tree
    - ufw
    - vim
  loop_control:
    label: "{{ item }}"
  become: yes

- name: packages | apt autoremove & autoclean
  apt:
    autoremove: true
    autoclean: true

- name: packages | enable clamav service
  systemd:
    name: clamav-daemon
    enabled: true
    state: started
