---
- name: Ensure development packages and libraries are installed
  apt:
    state: latest
    pkg: "{{ item }}"
  loop:
    - pipx
    - shellcheck
    - shfmt
    - universal-ctags
  loop_control:
    label: "{{ item }}"

- name: install development tools
  community.general.pipx:
    state: latest
    name: "{{ item }}"
    install_deps: true
  loop:
    - bandit
    - black
    - flake8
    - glances
    - pre-commit
    - ruff
    - yamlfmt
    - yamllint
  become: false

- name: Check if pipx path is present
  shell: test -d ~/.local/bin && echo "Pipx ensurepath executed" || echo "Pipx ensurepath not executed"
  register: pipx_ensurepath_output
  changed_when: false
  ignore_errors: true
  become: false

- name: Execute pipx ensurepath, if required
  command: pipx ensurepath
  when: pipx_ensurepath_output.rc != 0
  become: false
