---
- block:
    - name: apt packages tasks
      import_tasks: apt-packages.yml

    - name: ssh tasks
      import_tasks: ssh.yml

    - name: security tasks
      import_tasks: security.yml

    - name: optimize tasks
      import_tasks: optimize.yml

  tags: ['base']
